cptechinc/soft-dpluso

site/templates/_dbfunc.php
site/templates/content/confirm/quotes/outline.php
site/templates/content/edit/quotes/outline.php
site/templates/content/edit/quotes/quotehead-form.php
site/templates/content/edit/quotes/quotehead/phone-domestic.php
site/templates/redir/quotes-redir.php
site/templates/scripts/edit/edit-quotes.js
site/templates/styles/styles.css

Ability to review quote then decided where to go no next.

Quote confirm

---

site/templates/_head-blank.php
site/templates/_head-test.php
site/templates/_head.php
site/templates/_init.php
site/templates/content/ajax/load/ci-router.php
site/templates/content/ajax/load/ii-router.php
site/templates/cust-info.php
site/templates/item-info.php
site/templates/template-cart.php
site/templates/template-customer.php
site/templates/template-dashboard.php
site/templates/template-edit.php
site/templates/template-screen-formatters.php

JS and CSS files are added their file hash so if need be the cache is loaded if changes are made

JS CSS file versioning

---

site/templates/_dbfunc.php
site/templates/content/customer/cust-page/orders/orders-table.php
site/templates/content/customer/cust-page/orders/orders-thead-rows.php
site/templates/content/salesrep/orders/order-detail-rows.php
site/templates/content/salesrep/orders/order-documents-rows.php
site/templates/content/salesrep/orders/order-totals.php
site/templates/content/salesrep/orders/order-tracking-rows.php
site/templates/content/salesrep/orders/orders-panel.php
site/templates/content/salesrep/orders/orders-table.php
site/templates/content/salesrep/orders/orders-thead-rows.php
vendor/cptechinc/dpluso-processwire-classes/src/SalesOrder.class.php
vendor/cptechinc/dpluso-processwire-classes/src/SalesOrderPanel.class.php

created classes for the sales rep order table

Sales Rep Order Classes

---

composer.lock
site/templates/content/customer/cust-page/orders/orders-panel.php
site/templates/content/customer/cust-page/orders/orders-table.php
vendor/composer/installed.json
vendor/cptechinc/dpluso-processwire-classes/src/SalesOrder.class.php

Sales order class updates

---

site/templates/content/actions/actions-panel.php
site/templates/content/actions/stempf-actions-panel.php
vendor/cptechinc/dpluso-processwire-classes/src/UserActionPanel.class.php

generate add forms base on whatlist paneltype its showing

UserActionPanel class now makes the link to

---

site/templates/_dbfunc.php
site/templates/content/customer/cust-index/customer-index-table.php

Modified search query to look for vendID first and other fields after

#49 CRM Customer Searching

---

site/config.php
site/templates/_dbfunc.php
site/templates/_func.php
site/templates/_init.php
site/templates/content/customer/ajax/load/cust-index/ci-cust-list.php
site/templates/content/customer/ajax/load/cust-index/cust-list.php
site/templates/content/customer/ajax/load/cust-index/ii-cust-list.php
site/templates/content/customer/cust-index/customer-index-table.php
site/templates/content/vendor/ajax/load/vend-index/vi-vend-list.php
vendor/cptechinc/dpluso-processwire-classes/composer.json
vendor/cptechinc/dpluso-processwire-classes/src/Stringer.class.php
vendor/cptechinc/dpluso-processwire-classes/vendor/composer/autoload_classmap.php
vendor/cptechinc/dpluso-processwire-classes/vendor/composer/autoload_static.php

Creates Stringer Bell Class for string manipulation
Phone numbers can be searched without dashes
Exact CustIDS will be thrown to the top first.

Barbara cust search

---

site/templates/content/actions/tasks/reschedule-task.php
vendor/cptechinc/dpluso-processwire-classes/src/UserAction.class.php

Reschedule task modal title now shows more like the add task modal

---

site/templates/maintenance-page.php

created template file for maintenance-page
redirects to dashboard if there are no maintenance events open

#83 SalesPortal Maintenance

---

site/templates/_init.js.php
site/templates/content/common/phpjs/js-config.js.php
site/templates/content/cust-information/cust-sales-data.php

- added function to check if showcost is allowed for user
- added if statement on cust-sales-data page to display or not display cost depending on who is signed in

Costisplay with Permission

---

site/templates/_dbfunc.php

- converted functions to use QueryBuilder

#129 Quote Listing

---

site/templates/_init.js.php
site/templates/content/edit/pricing/tables/price-edit-table.php
site/templates/scripts/edit/edit-pricing.js

- added allow_belowminprice field to _init.js
- added error html message if price was below minimum
- added to change price funtion by adding if statement to check if price is allowed to go below minimum and error messages if it is not

#133 Edit Pricing

---

site/templates/content/ajax/load/quotes-router.php
site/templates/content/customer/cust-page/quotes/quote-search-form.php
site/templates/content/customer/cust-page/quotes/quotes-table.php
site/templates/content/customer/cust-page/quotes/quotes-thead-rows.php
site/templates/scripts/edit/edit-orders.js
site/templates/scripts/edit/edit-quotes.js

- changed save message for quotes and orders as "your changed have been saved" and "your changes have been submitted"
- added sales rep column to customer quote table

Quote Filtering

---

site/templates/content/customer/ajax/load/contacts/search-form.php
site/templates/content/customer/ajax/load/cust-index/search-form.php
site/templates/content/customer/cust-index/customer-index-form.php
site/templates/content/customer/cust-page/bookings/search-form..php
site/templates/content/customer/cust-page/quotes/search-form.php
site/templates/content/customer/cust-page/sales-history/search-form.php
site/templates/content/customer/cust-page/sales-orders/search-form.php
site/templates/content/dashboard/bookings/search-form.php
site/templates/content/dashboard/quotes/search-form.php
site/templates/content/dashboard/sales-history/search-form.php
site/templates/content/dashboard/sales-orders/search-form.php
site/templates/content/item-information/forms/item-activity-form.php
site/templates/content/item-information/forms/item-history-form.php
site/templates/content/item-information/forms/item-page-form.php
site/templates/content/products/ajax/load/product-results/product-cart-results.php
site/templates/content/vend-information/forms/purchase-history-form.php
site/templates/content/vend-information/forms/vend-page-form.php
site/templates/scripts/ci/cust-info.js
site/templates/template-login.php
vendor/cptechinc/dpluso-screen-formatters/src/ci/CustomerScreen.class.php
vendor/cptechinc/dpluso-screen-formatters/src/ii/ItemPageFormatter.class.php

- added "allow-enterkey-submit" class to forms that needed enter key submit

Form Fixes

---

site/templates/content/customer/contact/edit-contact.php

- added return to contact page button
- added return to  customer page button

Return Buttons for Contact Edit

---

site/templates/content/cart/cart-details.php
site/templates/content/confirm/orders/outline.php
site/templates/content/confirm/quotes/outline.php
site/templates/content/customer/cust-page/quotes/detail-rows.php
site/templates/content/customer/cust-page/quotes/table.php
site/templates/content/customer/cust-page/sales-history/detail-rows.php
site/templates/content/customer/cust-page/sales-history/table.php
site/templates/content/customer/cust-page/sales-orders/detail-rows.php
site/templates/content/customer/cust-page/sales-orders/table.php
site/templates/content/dashboard/quotes/detail-rows.php
site/templates/content/dashboard/quotes/table.php
site/templates/content/dashboard/sales-history/detail-rows.php
site/templates/content/dashboard/sales-history/table.php
site/templates/content/dashboard/sales-orders/detail-rows.php
site/templates/content/dashboard/sales-orders/table.php
site/templates/content/edit/orders/order-attachments.php
site/templates/content/edit/orders/order-details/order-details.php
site/templates/content/edit/orders/orderhead-form.php
site/templates/content/edit/quote-to-order/quote-details/quote-details.php
site/templates/content/edit/quotes/quote-attachments.php
site/templates/content/edit/quotes/quote-details/quote-details.php
site/templates/content/edit/quotes/quotehead-form.php
site/templates/redir/orders-redir.php
site/templates/scripts/edit/edit-orders.js
site/templates/template-email.php
site/templates/template-print.php

- generate_detailvieweditlink()
- generate_viewprintlink()
- generate_orderquotelink()
- generate_viewlinkeduseractionslink()
- generate_confirmationlink()
- generate_saveunlocklink()
- generate_confirmationlink()
- generate_saveunlockbutton()
- documentsrequestURL() -> generate_request_documentsURL()
* generate_dplusnotesrequestURL() -> generate_request_dplusnotesURL()
* generate_loaddetailsURL() -> generate_request_detailsURL()
* generate_sendemailurl() -> generate_sendemailURL()

Abstracton

---

README.md
site/templates/content/warehouse/menu.php
site/templates/updates.php
site/templates/warehouse-function.php

Warehouse Management Updates
Validate Warehouse Management permissions
- [ x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

Wm updates

---

composer.json
composer.lock
site/templates/_dbfunc.php
site/templates/_init.php
site/templates/configs/nav-config.php
site/templates/content/warehouse/inventory/print-item-label/inventory-results.php
site/templates/content/warehouse/inventory/print-item-label/item-details.php
site/templates/content/warehouse/inventory/print-item-label/item-form.php
site/templates/content/warehouse/inventory/print-item-label/labels-modal.php
site/templates/content/warehouse/inventory/print-item-label/page-logic.php
site/templates/content/warehouse/inventory/print-item-label/print-label-form.php
site/templates/content/warehouse/inventory/print-item-label/printers-modal.php
site/templates/redir/inventory.php
site/templates/scripts/warehouse/print-labels.js
site/templates/styles/styles.css
site/templates/updates.php
site/templates/warehouse-menu.php

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
If this is a relatively large or complex change, kic

Print Thermal Labels

---

site/templates/_head.php
site/templates/content/nav/nav-yt.php
site/templates/styles/styles.css

Navigation Bar is now not fixed

non-fixed nav

---

site/templates/_dbfunc.php
site/templates/content/customer/ajax/load/cust-index/ci-cust-list.php
site/templates/content/dashboard/bookings/bookings-panel.php
site/templates/content/dashboard/sales-panel/sales-panel.php

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
If this is a relatively large or complex change, kic

Customer search sort

---

site/templates/_dbfunc.php
site/templates/content/customer/ajax/load/cust-index/ci-cust-list.php
site/templates/content/customer/ajax/load/cust-index/search-form.php
site/templates/content/customer/ajax/load/cust-index/state-search-form.php
site/templates/scripts/scripts.js

- added function get_statesbylogin to dbfunc to list states user has customers in
- added $filter and $filtertypes to search_custindexedpaged and count_searchcustindex
- created state-search-form
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
If this is a relatively large or complex change, kic

Customer Search State Filter

---

composer.lock
site/templates/_dbfunc.php
site/templates/content/cust-information/ci-buttons.php
site/templates/content/cust-information/ci-customer-page.php
site/templates/content/cust-information/cust-sales-data.php
site/templates/content/customer/add/outline.php
site/templates/content/customer/add/prospect-outline.php
site/templates/content/customer/add/prospect-to-customer-outline.php
site/templates/content/customer/ajax/load/cust-index/ci-cust-list.php
site/templates/content/customer/ajax/load/cust-index/filter-search-form.php
site/templates/prospect-add.php
site/templates/prospect-to-customer-add.php
site/templates/redir/cust-redir.php

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
If this is a relatively large or complex change, kic

Add new prospect
